trigger:

    branches:
      include:
        - master

pr: none

pool:
    name: 'Unix'

jobs:
- job: henkem_kenya_ui_job
  variables:
  - group: FirebaseConfig

  steps:
  - task: replacetokens@5
    inputs:
      targetFiles: '$(Build.SourcesDirectory)/src/lib/firebase.ts'
      encoding: 'utf-8'
      tokenPattern: 'default'

  - task: NodeTool@0
    inputs:
      versionSpec: '18.x'
    displayName: 'Install Node.js'

  - task: NodeTool@0
    inputs:
      versionSpec: '18.x'
    displayName: 'Install dependancies'

  - script: |
      npm ci
    displayName: 'NPM CI'

  - task: NodeTool@0
    inputs:
      versionSpec: '18.x'
    displayName: 'Run project build'

  - script: |
      npm run build
    displayName: 'NPM RUN BUILD for first ui project'

  - task: ArchiveFiles@2
    displayName: 'Archive UI build files'
    inputs:
      rootFolderOrFile: '$(Build.SourcesDirectory)/dist'
      includeRootFolder: false
      archiveFile: '$(Build.ArtifactDirectory)/$(Build.BuildId).zip'
      archiveType: 'zip'
      replaceExistingArchive: true

  - task: PublishPipelineArtifact@1
    displayName: 'Publish UI artifact'
    inputs:
      targetPath: '$(Build.ArtifactDirectory)/$(Build.BuildId).zip'
      artifact: 'ui_artifact'
