trigger:

    branches:
      include:
        - master

pr: none

pool:
    name: 'Unix'

jobs:
- job: henkem_kenya_ui_job
  variables:
  - group: FirebaseConfig

  steps:
  - bash: |
      cat > $(Build.SourcesDirectory)/src/lib/firebase.config.json <<EOL
      {
        "apiKey": "$(API_KEY)",
        "authDomain": "$(AUTH_DOMAIN)",
        "databaseUrl": "$(DATABASE_URL)",
        "projectId": "$(PROJECT_ID)",
        "storageBucket": "$(STORAGE_BUCKET)",
        "messageSenderId": "$(MESSAGING_SENDER_ID)",
        "appId": "$(APP_ID)",
        "measurementId": "$(MEASUREMENT_ID)"
      }
      EOL
      echo "Generated firebase.config.json:"
    displayName: "Generate firebase config file."

  - task: NodeTool@0
    inputs:
      versionSpec: '18.x'
    displayName: 'Install Node.js'

  - task: NodeTool@0
    inputs:
      versionSpec: '18.x'
    displayName: 'Install dependancies'

  - script: |
      npm ci
    displayName: 'NPM CI'

  - task: NodeTool@0
    inputs:
      versionSpec: '18.x'
    displayName: 'Run project build'

  - script: |
      npm run build
    displayName: 'NPM RUN BUILD for first ui project'

  - task: ArchiveFiles@2
    displayName: 'Archive UI build files'
    inputs:
      rootFolderOrFile: '$(Build.SourcesDirectory)/dist'
      includeRootFolder: false
      archiveFile: '$(Build.ArtifactDirectory)/$(Build.BuildId).tar.gz'
      archiveType: 'tar'
      replaceExistingArchive: true

  - task: PublishPipelineArtifact@1
    displayName: 'Publish UI artifact'
    inputs:
      targetPath: '$(Build.ArtifactDirectory)/$(Build.BuildId).tar.gz'
      artifact: 'henkem_kenya_ui'
