trigger:

    branches:
      include:
        - master

pr: none

pool:
    name: 'Unix'

jobs:
- job: henkem_kenya_ui_job
  variables:
  - group: FirebaseConfig

  steps:
  - bash: |
      echo "##vso[task.setvariable variable=REACT_APP_API_KEY]$(API_KEY)"
      echo "##vso[task.setvariable variable=REACT_APP_AUTH_DOMAIN]$(AUTH_DOMAIN)"
      echo "##vso[task.setvariable variable=REACT_APP_DATABASE_URL]$(DATABASE_URL)"
      echo "##vso[task.setvariable variable=REACT_APP_PROJECT_ID]$(PROJECT_ID)"
      echo "##vso[task.setvariable variable=REACT_APP_STORAGE_BUCKET]$(STORAGE_BUCKET)"
      echo "##vso[task.setvariable variable=REACT_APP_MESSAGING_SENDER_ID]$(MESSAGING_SENDER_ID)"
      echo "##vso[task.setvariable variable=REACT_APP_APP_ID]$(APP_ID)"
      echo "##vso[task.setvariable variable=REACT_APP_MEASUREMENT_ID]$(MEASUREMENT_ID)"
    displayName: "Set Environment Variables"

  - bash: |
      cat > $(Build.SourcesDirectory)/src/lib/firebase.config.json <<EOL
      {
        "apiKey": "$(API_KEY)"
      }
      EOL
      echo "Generated firebase.config.json:"
      ls -lh $(Build.SourcesDirectory)/src/lib/firebase.config.json
      cat $(Build.SourceDirectory)/src/libfirebase.config.json
    displayName: "Generate firebase config file."

  - task: NodeTool@0
    inputs:
      versionSpec: '18.x'
    displayName: 'Install Node.js'

  - task: NodeTool@0
    inputs:
      versionSpec: '18.x'
    displayName: 'Install dependancies'

  - script: |
      npm ci
    displayName: 'NPM CI'

  - task: NodeTool@0
    inputs:
      versionSpec: '18.x'
    displayName: 'Run project build'

  - script: |
      npm run build
    displayName: 'NPM RUN BUILD for first ui project'

  - task: ArchiveFiles@2
    displayName: 'Archive UI build files'
    inputs:
      rootFolderOrFile: '$(Build.SourcesDirectory)/dist'
      includeRootFolder: false
      archiveFile: '$(Build.ArtifactDirectory)/$(Build.BuildId).tar.gz'
      archiveType: 'tar'
      replaceExistingArchive: true

  - task: PublishPipelineArtifact@1
    displayName: 'Publish UI artifact'
    inputs:
      targetPath: '$(Build.ArtifactDirectory)/$(Build.BuildId).tar.gz'
      artifact: 'henkem_kenya_ui'
