trigger: 
    paths:
      include:
        - '**/*'

pool: 
    name: 'Agent Luwi'
  
jobs:
- job: henkem_kenya_ui_job
  steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '18.x'
    displayName: 'Install Node.js'

  - task: NodeTool@0
    inputs:
      versionSpec: '18.x'
    displayName: 'Install dependancies'

  - script: |
      npm ci
    displayName: 'NPM CI'

  - task: NodeTool@0
    inputs:
      versionSpec: '18.x'
    displayName: 'Run project build'

  - script: |
      npm run build
    displayName: 'NPM RUN BUILD for first ui project'          

  - task: ArchiveFiles@2
    displayName: 'Archive UI build files'  
    condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
    inputs:
      rootFolderOrFile: '$(Build.SourcesDirectory)/dist'
      includeRootFolder: false
      archiveFile: '$(Build.ArtifactDirectory)/$(Build.BuildId).tar.gz'
      archiveType: 'tar'
      replaceExistingArchive: true

  - task: PublishPipelineArtifact@1
    displayName: 'Publish UI artifact'
    condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
    inputs:
      targetPath: '$(Build.ArtifactDirectory)/$(Build.BuildId).tar.gz'
      artifact: 'ui_artifact'          