name: Build henkem-kenya ui project

on:
  pull_request:
    branches:
      - master

jobs:
  build-ui:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Build ui project
        run: npm run build